version: '3.8'

services:
  aidocumentanalysis:
    container_name: aidocumentanalysis
    build:
      context: ./src/AIDocumentAnalysis
      dockerfile: Dockerfile
    depends_on:
      - ai-doc-analysis-storage

  ai-doc-analysis-storage:    
    container_name: aidocumentanalysis-storage
    build:
      context: .
      dockerfile: Docker/Database/Dockerfile
    environment:
      POSTGRES_DB: "AIDA"
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "LocalPassword#1"
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docker -d AIDA"]
      interval: 5s
      timeout: 5s
      retries: 5

  ai-doc-analysis-migration:
    container_name: aidocumentanalysis-migration
    image: liquibase/liquibase:4.10.0
    depends_on:
      ai-doc-analysis-storage:
        condition: service_healthy
    volumes:
      # We mount to /liquibase/changelog
      - ./Database/db_migration:/liquibase/changelog:ro    
    command: >
      --url="jdbc:postgresql://aidocumentanalysis-storage:5432/AIDA"
      --username=docker
      --password=LocalPassword#1
      --changeLogFile=changelog/changelog.xml
      update

volumes:
  db-data: